replicaCount: 1

image:
  repository: registry.gitlab.com
  tag: "registry.gitlab.com/bradenr/ledger-ui:"${{ image.tag }}
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "ledger-ui"

imagePullSecrets:
- name: gitlab-creds

imageCredentials:
- registry: registry.gitlab.com
  username: ${{ secrets.REGISTRY_USERNAME }}
  password: ${{ secrets.REGISTRY_PASSWORD }}
  secretName: gitlab-creds

container:
  ports:
  - 80
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http

ingress:
  enabled: true
  hosts:
  - host: ledger.braden.cc
    paths:
    - path: /
      port: 80
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
