replicaCount: 1

image:
  repository: ghcr.io/bradenrayhorn/ledger-ui
  tag: ${{ github.sha }}
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "ledger-ui"

imagePullSecrets:
- name: gitlab-creds

imageCredentials:
- registry: registry.gitlab.com
  username: ${{ secrets.REGISTRY_USERNAME }}
  password: ${{ secrets.REGISTRY_PASSWORD }}
  secretName: gitlab-creds

container:
  env:
  - name: REACT_APP_BASE_URL_AUTH
    value: "${{{ secrets.AUTH_BASE_URL }}}"
  ports:
  - 80
  livenessProbe:
    httpGet:
      path: /
      port: 80
  readinessProbe:
    httpGet:
      path: /
      port: 80

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  hosts:
  - host: ${{ secrets.HOST }}
    paths:
    - path: /
      port: 80
  tls:
  - hosts:
    - ${{ secrets.HOST }}
    secretName: ledger-ui-cert

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
