name: Run Tests and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test --ci

  build:
    name: Build Image
    needs:
      - test
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GitLab registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.gitlab.com/bradenr/ledger-ui:${{ github.sha }}

  deploy:
    name: Bake and deploy helm chart
    needs:
      - test
      - build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy
        uses: deliverybot/helm@v1
        with:
          namespace: ledger
          repository: https://bradenrayhorn.github.io/helm-charts/
          chart: webapp
          chart_version: 0.4.0
          track: stable
          helm: helm3
          release: ledger-ui
          version: ${{ github.sha }}
          atomic: true
          secrets: ${{ toJSON(secrets) }}
          value-files: >-
            [
              "values.yaml"
            ]
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
